[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About"
  url = "/about"
  weight = 20

[[main]]
  name = "Publications"
  url = "/publications"
  weight = 30

[[main]]
  name = "Projects"
  url = "/projects"
  weight = 40

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 50

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 60
